name: avatar_maker_anime
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  provider: ^6.0.5
  google_fonts: ^4.0.3
  http: ^0.13.5
  flutter_custom_tab_bar: ^1.2.1
  contained_tab_bar_view: ^0.8.0
  bottom_bar_matu: ^1.3.0
  dropdown_button2: ^2.0.0
  image_picker: ^0.8.7+1
  rotated_corner_decoration: ^2.1.0+1
  curved_navigation_bar: ^1.0.3
  flutter_staggered_animations: ^1.1.1
  wave_transition: ^0.0.6
  intl: ^0.17.0
  audioplayers: ^4.0.1
  carousel_slider: ^4.2.1
  swipe_cards: ^2.0.0+1
  get: ^4.6.5
  cherry_toast: ^1.2.1
  image_cropper: ^4.0.1
  path_provider: ^2.0.15
  encrypted_asset_image: ^0.0.1+2
  cached_network_image: ^3.2.3
  asset_cache: ^2.0.0
  widgets_to_image: ^0.0.2
  image_gallery_saver: ^2.0.1
  fluid_bottom_nav_bar: ^1.4.0
  marquee: ^2.2.3
  drop_shadow_image: ^0.9.1
  shared_preferences: ^2.0.20
  permission_handler: ^10.4.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ui_icon/
    - assets/ui_icon/page_intro.png
    - assets/part0_class0/
    - assets/part10_class10/
    - assets/part11_class11/
    - assets/part12_class12/
    - assets/part13_class13/
    - assets/part14_class14/
    - assets/part15_class15/
    - assets/part16_class16/
    - assets/part17_class17/
    - assets/part18_2class18/
    - assets/part19_class19/
    - assets/part1_class1/
    - assets/part2_class2/
    - assets/part3_class3/
    - assets/part4_class4/
    - assets/part5_class5/
    - assets/part6_class6/
    - assets/part7_class7/
    - assets/part8_class8/
    - assets/part9_class9/
