name: avatar_maker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  get: ^4.6.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.0.20
  permission_handler: ^11.3.1
  drop_shadow_image: ^0.9.1
  flutter_staggered_animations: ^1.1.1
  widgets_to_image: ^1.0.0
  image_gallery_saver:
    git:
      url: https://github.com/knottx/image_gallery_saver   # https://pub.dev/packages/image_gallery_saver
      ref: knottx
  flashy_tab_bar2: ^0.0.10
  fluentui_system_icons: ^1.1.264
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ui_icon/
    - assets/ui_icon/page_intro.png
    - assets/part0_class0/
    - assets/part10_class10/
    - assets/part11_class11/
    - assets/part12_class12/
    - assets/part13_class13/
    - assets/part14_class14/
    - assets/part15_class15/
    - assets/part16_class16/
    - assets/part17_class17/
    - assets/part18_2class18/
    - assets/part19_class19/
    - assets/part1_class1/
    - assets/part2_class2/
    - assets/part3_class3/
    - assets/part4_class4/
    - assets/part5_class5/
    - assets/part6_class6/
    - assets/part7_class7/
    - assets/part8_class8/
    - assets/part9_class9/
    - assets/update/part9_class9/
